describe('Todo MVC Test', function() {
	this.beforeEach(function(){
		cy.visit('http://todomvc.com/examples/jquery')
		cy.get(`.new-todo`)
		.type(`Add item 1{enter}`)
		.type(`Add item 2{enter}`)
		.type(`Add item 3{enter}`)
		.type(`Add item 4{enter}`)
	})
	it('should add an item ', function() {
		cy.get(`.new-todo`)
		.type(`Add item 5{enter}`)
	})
	it('should mark one item as completed', function() {
		cy.get(`.todo-list li`).eq(0).find(`.toggle`).check()
		cy.get(`.clear-completed`).should(`be.visible`)
		cy.get(`.filters > :nth-child(2) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 3)
		cy.get(`.filters > :nth-child(3) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 1)
	})
	it('should mark 2 items as completed', function() {
		cy.get(`.todo-list li`).eq(0).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(1).find(`.toggle`).check()
		cy.get(`.clear-completed`).should(`be.visible`)
		cy.get(`.filters > :nth-child(2) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 2)
		cy.get(`.filters > :nth-child(3) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 2)
	})
	it('should mark all items as completed', function() {
		cy.get(`.todo-list li`).eq(0).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(1).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(2).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(3).find(`.toggle`).check()
		cy.get(`.clear-completed`).should(`be.visible`)
		cy.get(`.filters > :nth-child(2) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 0)
		cy.get(`.filters > :nth-child(3) > a`).click()
		cy.get('.todo-list').find('li').should('have.length', 4)
	})
	it('should clear all completed items', function() {
		cy.get(`.todo-list li`).eq(0).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(1).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(2).find(`.toggle`).check()
		cy.get(`.todo-list li`).eq(3).find(`.toggle`).check()
		cy.get(`.clear-completed`).should(`be.visible`).click()
		cy.get('.todo-list').find('li').should('have.length', 0)
	})
  })